### PR TITLE
Add header and footer to application.hbs issue #3

### LINKED ISSUE #3: Add header and footer to application.hbs
Add the header and footer to the application.hbs file. 

If you're unsure of how to do this, look in the emberjs.com website repo.

### PR DESCRIPTION
**Pull request by fozy81**

### CODE REVIEW

**Comment by ijlee2** [comment]
This repo lacks actual code and is currently inactive. I'm not sure why this PR was made, but let's close it. I ran the app locally and saw that the `application` route only has a header and footer.

**Comment by fozy81** [comment]
Hi @ijlee2 the PR was for https://github.com/ember-learn/ember-survey/issues/3 - part of a series of small steps to migrate the [community surveys to a separate repo](https://github.com/orgs/ember-learn/projects/46#card-36028362). The issue had 'help wanted' to so I just quickly made the PR.

**Comment by ijlee2** [comment]
Ah, I see. I didn't see the issue 3, my bad. Let me check with Melanie on Monday the status of this repo.

**Comment by fozy81** [comment]
No worries, if this repo still required happy to contribute further. I had a quick go at moving the survey info across but will hold off any more work until confirmed.

**Comment by MelSumner** [comment]
@ijlee2 @fozy81 let's reopen the PR and get the code merged <3

**Comment by ijlee2** [comment]
@MelSumner Ok, sounds good. Thanks for your feedback!

**Review by ijlee2 — APPROVED** [review]

**Pull request merged**
