### PR TITLE
Markdown package

### PR DESCRIPTION
**Pull request by ChazJensen**
I'm pretty sure this is what you meant in issue #4 when you said you wanted the markdown package added, you can double check me by looking at the dependencies in `./packages.json`.
I've also added a folder, `./app/data` with a `tmp` file in it to check off the other checkbox you mentioned earlier.

### CODE REVIEW

**Review by MelSumner — CHANGES_REQUESTED** [review]
Thank you for submitting this PR! The addon is actually this one: https://www.npmjs.com/package/markdown-to-json 

If you would update that, I'd be happy to merge. Thank you for taking on this issue!

**Comment by ChazJensen** [comment]
is it a problem that their current build is unstable (marked as "failing")?

**Comment by ChazJensen** [comment]
Alright, this should be all good to go hopefully? Sorry about the two pull requests, I ended up confusing myself, but the markdown package was uninstalled and the mardown-to-json package was installed. This pull request should be ready (data folder is also included).

**Review by MelSumner — APPROVED** [review]
Thank you for making these changes!

**Pull request merged**
